name: Release

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - name: "Create Release"
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  darwin:
    name: Upload Darwin Binary
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build -c release --arch x86_64 --arch arm64
      - name: Set output
        run: echo "BIN_DIR=$(swift build -c release --arch x86_64 --arch arm64 --show-bin-path)" >> $GITHUB_ENV
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.BIN_DIR }}/wrangler
          asset_name: wrangler-darwin_arm64_x86_64
          tag: ${{ github.ref }}
          overwrite: true
          body: "TBA"
  linux:
    name: Upload Linux Binary
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build -c release
      - name: Set output
        run: echo "BIN_DIR=$(swift build -c release --show-bin-path)" >> $GITHUB_ENV
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.BIN_DIR }}/wrangler
          asset_name: wrangler-ubuntu-20.04_x86_64
          tag: ${{ github.ref }}
          overwrite: true
          body: "TBA"
  windows:
    name: Upload Windows Binary
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: MaxDesiatov/swift-windows-action@v1
        with:
          shell-action: swift build -c release
          swift-version: '5.5'
      - run: dir C:\Library
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .build/release/wrangler.exe
          asset_name: wrangler-win10_x86_64.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "TBA"