

name: Release

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - name: "Create Release"
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: Release
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build -c release --arch x86_64 --arch arm64
      - name: Set output
        run: echo "BIN_DIR=${swift build -c release --arch x86_64 --arch arm64 --show-bin-path}" >> $GITHUB_ENV
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.RELEASE_VERSION }}/wrangler
          asset_name: wrangler-darwin-universal
          tag: ${{ github.ref }}
          overwrite: true
          body: "TBA"