name: Release

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - name: "Create Release"
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  darwin:
    name: Upload Darwin Binary
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build -c release --arch x86_64 --arch arm64
      - name: Set output
        run: echo "BIN_DIR=$(swift build -c release --arch x86_64 --arch arm64 --show-bin-path)" >> $GITHUB_ENV
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.BIN_DIR }}/wrangler
          asset_name: wrangler-darwin_arm64_x86_64
          tag: ${{ github.ref }}
          overwrite: true
          body: "TBA"
  linux:
    name: Upload Linux Binary
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build -c release
      - name: Set output
        run: echo "BIN_DIR=$(swift build -c release --show-bin-path)" >> $GITHUB_ENV
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.BIN_DIR }}/wrangler
          asset_name: wrangler-ubuntu-20.04_x86_64
          tag: ${{ github.ref }}
          overwrite: true
          body: "TBA"
  windows:
    name: Upload Windows Binary
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: MaxDesiatov/swift-windows-action@v1
        with:
          shell-action: swift build -c release
          swift-version: '5.5'
      - name: Prepare executable
        run: |
          md bin
          xcopy .build/release/wrangler.exe bin
      - name: Prepare dll
        run: |
          xcopy C:\Library\icu-67\usr\bin\icudt67.dll bin
          xcopy C:\Library\icu-67\usr\bin\icuin67.dll bin
          xcopy C:\Library\icu-67\usr\bin\icuuc67.dll bin
          xcopy C:\Library\Swift-development\bin\BlocksRuntime.dll bin
          xcopy C:\Library\Swift-development\bin\dispatch.dll bin
          xcopy C:\Library\Swift-development\bin\Foundation.dll bin
          xcopy C:\Library\Swift-development\bin\FoundationNetworking.dll bin
          xcopy C:\Library\Swift-development\bin\FoundationXML.dll bin
          xcopy C:\Library\Swift-development\bin\swiftCore.dll bin
          xcopy C:\Library\Swift-development\bin\swiftCRT.dll bin
          xcopy C:\Library\Swift-development\bin\swiftDispatch.dll bin
          xcopy C:\Library\Swift-development\bin\swiftWinSDk.dll bin
      - name: Packing
        run: powershell Compress-Archive bin bin.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin.zip
          asset_name: wrangler-win10_x86_64.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "TBA"